### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by ChristophHeilmann** [myfreeer/chrome-pak-customizer#1]
Hi,

I got an index out of range error when I tried to unpack a chrome string resource (see attachment):

C:\Users\Günter\Documents\Raccoon\com.android.chrome_65.0.3325.109-332510901_minAPI21(armeabi-v7a)(nodpi)\full-package-win32-and-win64>unpack
node-chrome-pak
Written by Hwang, C. W. (hikipro95@gmail.com)

unpacking at C:\Users\Günter\Documents\Raccoon\com.android.chrome_65.0.3325.109-332510901_minAPI21(armeabi-v7a)(nodpi)\full-package-win32-and-win64\\unpacked
buffer.js:830
    throw new RangeError('Index out of range');
    ^
RangeError: Index out of range
    at checkOffset (buffer.js:830:11)
    at Buffer.readUInt32BE (buffer.js:904:5)
    at unpack_proc (C:\Users\Günter\Documents\Raccoon\com.android.chrome_65.0.3325.109-332510901_minAPI21(armeabi-v7a)(nodpi)\full-package-win32-and-win64\node-chrome-pak.js:159:21)
    at Object.<anonymous> (C:\Users\Günter\Documents\Raccoon\com.android.chrome_65.0.3325.109-332510901_minAPI21(armeabi-v7a)(nodpi)\full-package-win32-and-win64\node-chrome-pak.js:36:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)

Gewartet wird 1 Sekunden. Weiter mit beliebiger Taste...

C:\Users\Günter\Documents\Raccoon\com.android.chrome_65.0.3325.109-332510901_minAPI21(armeabi-v7a)(nodpi)\full-package-win32-and-win64>

pak file:
[de.zip](https://github.com/myfreeer/chrome-pak-customizer/files/1887432/de.zip)

**Comment by myfreeer** [comment]
I have pushed a quick fix but is seems google had changed pak format in recent versions, I'll look into it if i got free time.
